//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from messageformat.g4 by ANTLR 4.1-SNAPSHOT

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ImessageformatListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.1-SNAPSHOT")]
public partial class messageformatBaseListener : ImessageformatListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgNumber([NotNull] messageformatParser.ArgNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgNumber([NotNull] messageformatParser.ArgNumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] messageformatParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] messageformatParser.ArgumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] messageformatParser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] messageformatParser.MessageContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argNameOrNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgNameOrNumber([NotNull] messageformatParser.ArgNameOrNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argNameOrNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgNameOrNumber([NotNull] messageformatParser.ArgNameOrNumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.messageText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageText([NotNull] messageformatParser.MessageTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.messageText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageText([NotNull] messageformatParser.MessageTextContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.style"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStyle([NotNull] messageformatParser.StyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.style"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStyle([NotNull] messageformatParser.StyleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.noneArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneArg([NotNull] messageformatParser.NoneArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.noneArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneArg([NotNull] messageformatParser.NoneArgContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] messageformatParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] messageformatParser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.simpleArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleArg([NotNull] messageformatParser.SimpleArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.simpleArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleArg([NotNull] messageformatParser.SimpleArgContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgName([NotNull] messageformatParser.ArgNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgName([NotNull] messageformatParser.ArgNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
