//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from messageformat.g4 by ANTLR 4.1-SNAPSHOT
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="messageformatParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.1-SNAPSHOT")]
public interface ImessageformatListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] messageformatParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] messageformatParser.SelectorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] messageformatParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] messageformatParser.ArgumentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgNumber([NotNull] messageformatParser.ArgNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgNumber([NotNull] messageformatParser.ArgNumberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.messageText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageText([NotNull] messageformatParser.MessageTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.messageText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageText([NotNull] messageformatParser.MessageTextContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.pluralArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPluralArg([NotNull] messageformatParser.PluralArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.pluralArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPluralArg([NotNull] messageformatParser.PluralArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.offsetValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffsetValue([NotNull] messageformatParser.OffsetValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.offsetValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffsetValue([NotNull] messageformatParser.OffsetValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] messageformatParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] messageformatParser.KeywordContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.pluralStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPluralStyle([NotNull] messageformatParser.PluralStyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.pluralStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPluralStyle([NotNull] messageformatParser.PluralStyleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.simpleArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleArg([NotNull] messageformatParser.SimpleArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.simpleArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleArg([NotNull] messageformatParser.SimpleArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] messageformatParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] messageformatParser.TypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage([NotNull] messageformatParser.MessageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage([NotNull] messageformatParser.MessageContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argNameOrNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgNameOrNumber([NotNull] messageformatParser.ArgNameOrNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argNameOrNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgNameOrNumber([NotNull] messageformatParser.ArgNameOrNumberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStyle([NotNull] messageformatParser.StyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStyle([NotNull] messageformatParser.StyleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.noneArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneArg([NotNull] messageformatParser.NoneArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.noneArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneArg([NotNull] messageformatParser.NoneArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.explicitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitValue([NotNull] messageformatParser.ExplicitValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.explicitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitValue([NotNull] messageformatParser.ExplicitValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="messageformatParser.argName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgName([NotNull] messageformatParser.ArgNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="messageformatParser.argName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgName([NotNull] messageformatParser.ArgNameContext context);
}
